In [156]:
import mujoco_py
import numpy as np

In [157]:
# creacion del modelo del robot
model = mujoco_py.load_model_from_path("RobotEnv/assets/UR5/robotModelV2.xml")
sim = mujoco_py.MjSim(model)
#viewer = mujoco_py.MjViewer(sim)

In [158]:
sim_state = sim.get_state()
print(sim_state)
controller = np.copy(sim.data.ctrl).flatten()
print("señal de control",controller)
print("posicion de las articulaciones",sim.data.qpos)
init_position = sim.data.qpos.ravel().copy()
print(init_position)

MjSimState(time=0.0, qpos=array([0., 0., 0., 0., 0., 0.]), qvel=array([0., 0., 0., 0., 0., 0.]), act=None, udd_state={})
señal de control [0. 0. 0. 0. 0. 0.]
posicion de las articulaciones [0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


In [159]:
sim.data.qpos[0] = 0
print("antes del control",sim.data.qpos[0])
controller[:] = 1
sim.step()
print("despues del control",sim.data.qpos[0])
print(controller)

antes del control 0.0
despues del control 2.786903368567068e-09
[1. 1. 1. 1. 1. 1.]


In [211]:
target_bounds = np.array(((0.1, 0.2), (0.4, 0.5), (0.5, 0.6)))
goal = np.random.rand(3) * (target_bounds[:, 1] - target_bounds[:, 0] 
                           ) + target_bounds[:, 0]
print(target_bounds)
print(goal)
print(target_bounds[:,1] - target_bounds[:,0] + target_bounds[:,0])

[[0.1 0.2]
 [0.4 0.5]
 [0.5 0.6]]
[0.16460377 0.48783695 0.53088679]
[0.2 0.5 0.6]


In [212]:
x = np.linalg.norm(0.5 - 2)
print(x)

1.5


In [2]:
!jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [4]:
!jt -t grade3